name: Update README

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Update README and User Docs
        run: node .github/scripts/updateDocs.js

      - name: Commit and Push changes
        run: |
          git config --local user.email "rud167637@gmail.com"
          git config --local user.name "rud1676"
          git add README.md id/*.md
          git commit -m "Update README and user docs" -a || echo "No changes to commit"
          git push
